"""Initial check

Revision ID: e274c084bbc9
Revises: 
Create Date: 2023-09-24 14:37:37.485240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e274c084bbc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table("users", 
                    sa.Column("id", sa.Integer(), primary_key=True, unique=True),
                    sa.Column("user_id", sa.BigInteger()),
                    sa.Column("username", sa.String()),
                    sa.Column("balance", sa.Integer(), default=0),
                    sa.Column("banned", sa.Integer(), default=0),
                    sa.Column("time_start", sa.BigInteger(), default=0))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
